import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MobileNav from "@/components/MobileNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plex = IBM_Plex_Sans({
  subsets: ["latin", "latin-ext"], // include latin-ext for Romanian diacritics
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-plex-sans", // exposes a CSS var
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ro" className={plex.variable}>
      <body className="font-sans">
        <MobileNav />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
